
package Afficherinformations;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
public class affichageinterface extends javax.swing.JFrame {
    
     private Connection con;
      public affichageinterface() {
        initComponents();
       
        
    }
    
    public affichageinterface(Connection con) {
        initComponents();
        this.con=con;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ouvexistants = new javax.swing.JButton();
        ouvragesdisponibles = new javax.swing.JButton();
        ouvragesprêtés = new javax.swing.JButton();
        ouvragesenpossession = new javax.swing.JButton();
        ouvrageleplusdemandé = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        desktopPanecontrol = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("affiche form");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        ouvexistants.setBackground(new java.awt.Color(0, 102, 255));
        ouvexistants.setFont(new java.awt.Font("Baskerville Old Face", 2, 18)); // NOI18N
        ouvexistants.setForeground(new java.awt.Color(255, 255, 255));
        ouvexistants.setText("Ouvrages Existants");
        ouvexistants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouvexistantsActionPerformed(evt);
            }
        });

        ouvragesdisponibles.setBackground(new java.awt.Color(0, 102, 255));
        ouvragesdisponibles.setFont(new java.awt.Font("Baskerville Old Face", 2, 18)); // NOI18N
        ouvragesdisponibles.setForeground(new java.awt.Color(255, 255, 255));
        ouvragesdisponibles.setText("Ouvrages Disponibles");
        ouvragesdisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouvragesdisponiblesActionPerformed(evt);
            }
        });

        ouvragesprêtés.setBackground(new java.awt.Color(0, 102, 255));
        ouvragesprêtés.setFont(new java.awt.Font("Baskerville Old Face", 2, 18)); // NOI18N
        ouvragesprêtés.setForeground(new java.awt.Color(255, 255, 255));
        ouvragesprêtés.setText("Ouvrages Prêtés");
        ouvragesprêtés.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouvragesprêtésActionPerformed(evt);
            }
        });

        ouvragesenpossession.setBackground(new java.awt.Color(0, 102, 255));
        ouvragesenpossession.setFont(new java.awt.Font("Baskerville Old Face", 2, 18)); // NOI18N
        ouvragesenpossession.setForeground(new java.awt.Color(255, 255, 255));
        ouvragesenpossession.setText("Ouvrages En Possession");
        ouvragesenpossession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouvragesenpossessionActionPerformed(evt);
            }
        });

        ouvrageleplusdemandé.setBackground(new java.awt.Color(0, 102, 255));
        ouvrageleplusdemandé.setFont(new java.awt.Font("Baskerville Old Face", 2, 18)); // NOI18N
        ouvrageleplusdemandé.setForeground(new java.awt.Color(255, 255, 255));
        ouvrageleplusdemandé.setText("L'ouvrage Le plus Demandé");
        ouvrageleplusdemandé.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouvrageleplusdemandéActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ouvrageleplusdemandé, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ouvragesenpossession, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(ouvragesprêtés, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ouvragesdisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ouvexistants, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(ouvexistants, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ouvragesdisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ouvragesprêtés, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ouvragesenpossession, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ouvrageleplusdemandé, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Que voulez-vous  Afficher ?");

        javax.swing.GroupLayout desktopPanecontrolLayout = new javax.swing.GroupLayout(desktopPanecontrol);
        desktopPanecontrol.setLayout(desktopPanecontrolLayout);
        desktopPanecontrolLayout.setHorizontalGroup(
            desktopPanecontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPanecontrolLayout.setVerticalGroup(
            desktopPanecontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 393, Short.MAX_VALUE))
                    .addComponent(desktopPanecontrol))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(desktopPanecontrol))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ouvexistantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouvexistantsActionPerformed
        desktopPanecontrol.removeAll();
        OuvragesExi Ouvexi = new OuvragesExi (con);//jinternalframe object
        desktopPanecontrol.add(Ouvexi).setVisible(true);
        desktopPanecontrol.updateUI();// bch tsaker w t7el 7aja jdida
    }//GEN-LAST:event_ouvexistantsActionPerformed

    private void ouvragesprêtésActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouvragesprêtésActionPerformed
        desktopPanecontrol.removeAll();
        OuvragesPrêtés OuvPre = new OuvragesPrêtés(con);//jinternalframe object
        desktopPanecontrol.add(OuvPre).setVisible(true);
        desktopPanecontrol.updateUI();// bch tsaker w t7el 7aja jdida
    }//GEN-LAST:event_ouvragesprêtésActionPerformed

    private void ouvragesenpossessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouvragesenpossessionActionPerformed
        desktopPanecontrol.removeAll();
        OuvragesEnPossession OuvEnPoss = new OuvragesEnPossession(con);//jinternalframe object
        desktopPanecontrol.add(OuvEnPoss).setVisible(true);
        desktopPanecontrol.updateUI();
    }//GEN-LAST:event_ouvragesenpossessionActionPerformed

    private void ouvragesdisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouvragesdisponiblesActionPerformed
        desktopPanecontrol.removeAll();
        OvragesDisponibles OuvDispo = new OvragesDisponibles(con);//jinternalframe object
        desktopPanecontrol.add(OuvDispo).setVisible(true);
        desktopPanecontrol.updateUI();
    }//GEN-LAST:event_ouvragesdisponiblesActionPerformed

    private void ouvrageleplusdemandéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouvrageleplusdemandéActionPerformed
        desktopPanecontrol.removeAll();
       OuvrageLePlusDemandé ouvdeaman = new OuvrageLePlusDemandé(con);//jinternalframe object
        desktopPanecontrol.add(ouvdeaman).setVisible(true);
        desktopPanecontrol.updateUI();
    }//GEN-LAST:event_ouvrageleplusdemandéActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPanecontrol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ouvexistants;
    private javax.swing.JButton ouvrageleplusdemandé;
    private javax.swing.JButton ouvragesdisponibles;
    private javax.swing.JButton ouvragesenpossession;
    private javax.swing.JButton ouvragesprêtés;
    // End of variables declaration//GEN-END:variables
}
