/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aminb
 */
package gerer;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class GestionCompte extends javax.swing.JFrame {
    
    Pattern idPattern=Pattern.compile("^[0-9]+$");
    Pattern loginPattern=Pattern.compile("^[a-zA-Z0-9_-]{3,25}$");
    Pattern nomPattern = Pattern.compile("^[a-zA-z]+([\\s][a-zA-Z]+)*$");
    Pattern passwordPattern = Pattern.compile("^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$");
    
    Connection con;
    Color selected=new Color(111,202,233);
    Color notselected=new Color(56,182,225);
    String currentCard="card2";
    Bibliothecaire updateBiblio;
    Compte updateCompte;
    
    /**
     * Creates new form App
     */
    public GestionCompte() {
        initComponents();
        try{
            // Connect to DB
            String host = "jdbc:mysql://localhost:3306/biblio";
            String nName = "root";
            String uPass = "root";
            con= DriverManager.getConnection(host,nName,uPass);
            System.out.println("Connected to DB");
            Statement stmt = con.createStatement();
            String query1="SET information_schema_stats_expiry = 0;";
            stmt.executeUpdate(query1);
        }
        catch (SQLException err){
            System.out.println(err.getMessage());
        }
    }
    
    public void setBackground(){
        ajoutPanel.setBackground(notselected);
        editPanel.setBackground(notselected);
    }
    
    public void clearUpdate(){
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jLabel13.setText("");
        jLabel15.setText("");
        jLabel16.setText("");
        jLabel20.setText("");
        jLabel22.setText("");
    }
    public void clearAjout(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
        jLabel1.setText("");
        jLabel3.setText("");
        jLabel4.setText("");
        jLabel17.setText("");
        jLabel24.setText("");
        jLabel27.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();
        retourPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        ajoutPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        editPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        discPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        ajoutAdh = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        majAdh = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Adherent");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navPanel.setBackground(new java.awt.Color(56, 182, 255));
        navPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        retourPanel.setBackground(new java.awt.Color(56, 182, 255));
        retourPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retourPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                retourPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                retourPanelMouseExited(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(18, 18, 18));
        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow.png"))); // NOI18N
        jLabel23.setText("     Retour");
        jLabel23.setHorizontalAlignment(JLabel.CENTER);

        javax.swing.GroupLayout retourPanelLayout = new javax.swing.GroupLayout(retourPanel);
        retourPanel.setLayout(retourPanelLayout);
        retourPanelLayout.setHorizontalGroup(
            retourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        retourPanelLayout.setVerticalGroup(
            retourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        navPanel.add(retourPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        ajoutPanel.setBackground(new java.awt.Color(110, 202, 233));
        ajoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajoutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajoutPanelMouseExited(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(7, 213, 224));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(JLabel.CENTER);
        jLabel10.setText("Ajout Compte Bibliothecaire");

        javax.swing.GroupLayout ajoutPanelLayout = new javax.swing.GroupLayout(ajoutPanel);
        ajoutPanel.setLayout(ajoutPanelLayout);
        ajoutPanelLayout.setHorizontalGroup(
            ajoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutPanelLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ajoutPanelLayout.setVerticalGroup(
            ajoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        navPanel.add(ajoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, 200, 45));

        editPanel.setBackground(new java.awt.Color(56, 182, 255));
        editPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editPanelMouseExited(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(64, 43, 100));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(JLabel.CENTER);
        jLabel11.setText("Editer Compte Bibliothecaire");

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        navPanel.add(editPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 45));

        discPanel.setBackground(new java.awt.Color(56, 182, 255));
        discPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                discPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                discPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                discPanelMouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(18, 18, 18));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/power.png"))); // NOI18N
        jLabel9.setText("     Deconnecter");
        jLabel9.setHorizontalAlignment(JLabel.CENTER);

        javax.swing.GroupLayout discPanelLayout = new javax.swing.GroupLayout(discPanel);
        discPanel.setLayout(discPanelLayout);
        discPanelLayout.setHorizontalGroup(
            discPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        discPanelLayout.setVerticalGroup(
            discPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        navPanel.add(discPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 406, 200, 45));

        getContentPane().add(navPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 451));

        mainPanel.setLayout(new java.awt.CardLayout());

        ajoutAdh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Nom");
        jLabel5.setMaximumSize(new java.awt.Dimension(50, 10));
        jLabel5.setMinimumSize(new java.awt.Dimension(50, 10));
        jLabel5.setPreferredSize(new java.awt.Dimension(50, 10));
        ajoutAdh.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 170, 40));
        ajoutAdh.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 180, 40));

        jLabel6.setText("Prenom");
        ajoutAdh.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 170, 40));
        ajoutAdh.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 180, 40));

        jLabel7.setText("Login");
        ajoutAdh.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 170, 40));
        ajoutAdh.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 180, 40));

        jLabel8.setText("Mot de passe");
        ajoutAdh.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 170, 40));

        jButton5.setText("Annuler");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        ajoutAdh.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 160, 40));

        jButton6.setText("Confirmer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        ajoutAdh.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 160, 40));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        ajoutAdh.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 180, 30));

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        ajoutAdh.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 180, 30));

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        ajoutAdh.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 180, 30));

        jLabel17.setBackground(new java.awt.Color(255, 0, 0));
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        ajoutAdh.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 180, 30));

        jLabel24.setForeground(new java.awt.Color(0, 153, 0));
        ajoutAdh.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 360, 30));
        jLabel24.setHorizontalAlignment(JLabel.CENTER);

        jLabel26.setText("Confirmation Mot de passe");
        ajoutAdh.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 170, 40));

        jLabel27.setBackground(new java.awt.Color(255, 0, 0));
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        ajoutAdh.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 180, 30));
        ajoutAdh.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 180, 40));
        ajoutAdh.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 180, 40));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/view.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        ajoutAdh.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 40, 40));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/information.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        ajoutAdh.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 40, 40));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/view.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        ajoutAdh.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 40, 40));

        mainPanel.add(ajoutAdh, "card2");

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Nom");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 50, 150, 40));
        jPanel7.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 150, 40));

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 150, 30));

        jLabel14.setText("Prenom");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, 40));
        jPanel7.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 150, 40));

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 150, 30));

        jLabel19.setText("Login");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 40));
        jPanel7.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 150, 40));

        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 150, 30));

        jLabel21.setText("Mot de passe");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 150, 40));
        jPanel7.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 150, 40));

        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 150, 30));

        jButton4.setText("Confirmer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 130, 40));

        jButton7.setText("Annuler");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 130, 40));
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 310, 30));

        jPanel8.setBorder(BorderFactory.createMatteBorder(0,1,0,0,Color.black));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/loupe.png"))); // NOI18N
        jLabel2.setText("ID");
        jLabel2.setHorizontalAlignment(JLabel.CENTER);
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 70, 50));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 157, 50));

        jButton1.setText("Inserer donnees");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 157, 35));

        jButton2.setText("Effacer Bibliothecaire");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 157, 35));

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 157, 20));

        javax.swing.GroupLayout majAdhLayout = new javax.swing.GroupLayout(majAdh);
        majAdh.setLayout(majAdhLayout);
        majAdhLayout.setHorizontalGroup(
            majAdhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(majAdhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        majAdhLayout.setVerticalGroup(
            majAdhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPanel.add(majAdh, "card3");

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Ajout Bibliothecaire Inserer Donnees
        Matcher matcher = idPattern.matcher(jTextField5.getText());
        boolean matchFound = matcher.find();
        if(!matchFound) {
            jLabel16.setText("ID invalide");
        }
        else {
            jLabel16.setText("");
            try{
                Statement stmt = con.createStatement();
                String query = "SELECT * from bibliothecaire WHERE id_biblio="+jTextField5.getText()+"";
                ResultSet rs = stmt.executeQuery(query);
                if (rs.next()){
                    updateBiblio = new Bibliothecaire(Integer.parseInt(jTextField5.getText()),con);
                    jTextField6.setText(updateBiblio.getNom());
                    jTextField7.setText(updateBiblio.getPrenom());
                    jTextField8.setText(updateBiblio.getLogin());
                    updateCompte = new Compte(updateBiblio.getLogin(), con);
                    jTextField9.setText(updateCompte.getMdp());
                }
                else{
                    jLabel16.setText("Aucun bibliothecaire avec cette id");
                }
            }
            catch(SQLException err){
                System.out.println("Erreur insertion bibliothecaire");
                System.out.println(err.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jLabel13.setText("");
        jLabel15.setText("");
        jLabel20.setText("");
        jLabel22.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // Confirmer MAJ Adh
        jLabel13.setText("");jLabel15.setText("");jLabel20.setText("");jLabel22.setText("");jLabel16.setText("");jLabel18.setText("");
        Boolean t=true;
        String inputNom = jTextField6.getText();
        String inputPrenom = jTextField7.getText();
        String inputLogin = jTextField8.getText();
        String inputMdp = jTextField9.getText();
        Matcher matcher;
        
        if (updateBiblio==null){
            jLabel16.setText("Aucun bibliothecaire choisi");
            return;
        }
        
        matcher = nomPattern.matcher(inputNom);
        if(!matcher.find()) {
            t=false;
            jLabel13.setText("Nom invalide");
        }
        matcher = nomPattern.matcher(inputPrenom);
        if(!matcher.find()) {
            t=false;
            jLabel15.setText("Prenom invalide");
        }
        matcher = loginPattern.matcher(inputLogin);
        if(!matcher.find()) {
            t=false;
            jLabel20.setText("Login invalide");
        }
        matcher = passwordPattern.matcher(inputMdp);
        if(!matcher.find()) {
            t=false;
            jLabel22.setText("Mot de passe invalide");
        }
        if (t){
            try{
                Statement stmt = con.createStatement();
                String query1 = "SELECT * FROM compte WHERE login='"+inputLogin+"'";
                ResultSet rs = stmt.executeQuery(query1);
                if (rs.next() && !updateBiblio.getLogin().equals(inputLogin)){
                    t=false;
                    jLabel22.setText("Login deja utilisé");
                }
            }
            catch (SQLException err){
                System.out.println("Erreur ajout");
                System.out.println(err.getMessage());
            }
        }
        if (t){
            updateBiblio.setNom(jTextField6.getText());
            updateBiblio.setPrenom(jTextField7.getText());
            if (!inputLogin.equals(updateBiblio.getLogin())){
                String oldLogin = updateBiblio.getLogin();
                Compte compte = new Compte(inputLogin, inputMdp, con);
                updateBiblio.setLogin(inputLogin);
                updateBiblio.updateDB(con);
                Compte.delDB(oldLogin, con);
            }
            else{
                updateCompte.setMdp(inputMdp);
                updateCompte.updateDB(con);
                updateBiblio.updateDB(con);
            }
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // Supprimer Adh
        jLabel16.setText("");
        Matcher matcher = idPattern.matcher(jTextField5.getText());
        boolean matchFound = matcher.find();
        if(!matchFound) {
            jLabel16.setText("ID invalide");
            return;
        }
        try{
            Statement stmt = con.createStatement();
            String query = "SELECT * from bibliothecaire WHERE id_biblio="+Integer.parseInt(jTextField5.getText());
            ResultSet rs = stmt.executeQuery(query);
            if (rs.next()){
                int input = JOptionPane.showConfirmDialog(null, "Confirmer la supression","Confirmation",JOptionPane.OK_CANCEL_OPTION);
                if (input==0){
                    jLabel16.setText("");
                    Bibliothecaire biblio = new Bibliothecaire(Integer.parseInt(jTextField5.getText()), con);
                    Bibliothecaire.delDB(Integer.parseInt(jTextField5.getText()), con);
                    Compte.delDB(biblio.getLogin(), con);
                    JOptionPane.showMessageDialog(null, "Bibliothecaire supprimé avec succès");
                }
            }
            else{
                jLabel16.setText("Aucun bibliothecaire avec cette id");
            }
        }
        catch(SQLException err){
            System.out.println("Erreur suppression bibliothecaire");
            System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        // Ajouter Adh Confirmer
        jLabel1.setText("");jLabel3.setText("");jLabel4.setText("");jLabel17.setText("");jLabel27.setText("");jLabel24.setText("");
        Boolean t=true;
        String inputNom = jTextField1.getText();
        String inputPrenom = jTextField2.getText();
        String inputLogin = jTextField3.getText();
        String inputMdp = new String(jPasswordField1.getPassword());
        String inputConfirm = new String(jPasswordField2.getPassword());
        Matcher matcher;
        
        matcher = nomPattern.matcher(inputNom);
        if(!matcher.find()) {
            t=false;
            jLabel1.setText("Nom invalide");
        }
        matcher = nomPattern.matcher(inputPrenom);
        if(!matcher.find()) {
            t=false;
            jLabel3.setText("Prenom invalide");
        }
        matcher = loginPattern.matcher(inputLogin);
        if(!matcher.find()) {
            t=false;
            jLabel4.setText("Login invalide");
        }
        matcher = passwordPattern.matcher(inputMdp);
        if(!matcher.find()) {
            t=false;
            jLabel17.setText("Tel invalide");
        }
        matcher = passwordPattern.matcher(inputMdp);
        if(!inputMdp.equals(inputConfirm)) {
            t=false;
            jLabel27.setText("Confirmation incorrecte");
        }
        if (t){
            try{
                Statement stmt = con.createStatement();
                String query1 = "SELECT * FROM compte WHERE login='"+inputLogin+"'";
                ResultSet rs = stmt.executeQuery(query1);
                if (rs.next()){
                    t=false;
                    jLabel4.setText("Login deja utilisé");
                }
            }
            catch (SQLException err){
                System.out.println("Erreur ajout");
                System.out.println(err.getMessage());
            }
        }
        
        if (t){
           Compte compte = new Compte(inputLogin, inputMdp, con);
           Bibliothecaire biblio = new Bibliothecaire(inputNom, inputPrenom, inputLogin, con);
           jLabel24.setText("Client cree avec succes avec l'id: "+biblio.id);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        clearAjout();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void discPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discPanelMouseExited
        // TODO add your handling code here:
        discPanel.setBackground(notselected);
    }//GEN-LAST:event_discPanelMouseExited

    private void discPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discPanelMouseEntered
        // TODO add your handling code here:
        // Disconnect
        discPanel.setBackground(selected);
    }//GEN-LAST:event_discPanelMouseEntered

    private void editPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPanelMouseExited
        // TODO add your handling code here:
        if (!currentCard.equals("card3")){
            editPanel.setBackground(notselected);
        }
    }//GEN-LAST:event_editPanelMouseExited

    private void editPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPanelMouseEntered
        // TODO add your handling code here:
        editPanel.setBackground(selected);
    }//GEN-LAST:event_editPanelMouseEntered

    private void editPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPanelMouseClicked
        // TODO add your handling code here:
        // Editer Bibliothecaire
        clearAjout();
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card3");
        currentCard="card3";
        setBackground();
        editPanel.setBackground(selected);
    }//GEN-LAST:event_editPanelMouseClicked

    private void ajoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutPanelMouseClicked
        // TODO add your handling code here:
        // Ajouter Bibliothecaire
        clearUpdate();
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card2");
        currentCard="card2";
        setBackground();
        ajoutPanel.setBackground(selected);
    }//GEN-LAST:event_ajoutPanelMouseClicked

    private void ajoutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutPanelMouseEntered
        // TODO add your handling code here:
        ajoutPanel.setBackground(selected);
    }//GEN-LAST:event_ajoutPanelMouseEntered

    private void ajoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutPanelMouseExited
        // TODO add your handling code here:
        if (!currentCard.equals("card2")){
            ajoutPanel.setBackground(notselected);
        }
    }//GEN-LAST:event_ajoutPanelMouseExited

    private void retourPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourPanelMouseExited
        // TODO add your handling code here:
        retourPanel.setBackground(notselected);
    }//GEN-LAST:event_retourPanelMouseExited

    private void retourPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourPanelMouseEntered
        // TODO add your handling code here:
        retourPanel.setBackground(selected);
    }//GEN-LAST:event_retourPanelMouseEntered

    private void retourPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourPanelMouseClicked
        // TODO add your handling code here:
        if (currentCard=="card4"){
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "card3");
            currentCard="card3";
            setBackground();
            editPanel.setBackground(selected);
        }
    }//GEN-LAST:event_retourPanelMouseClicked

    private void discPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discPanelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_discPanelMouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Le mot de passe doit contenir: \n• Entre 8 et 25 caractères\n• Au moins un caractère majuscule\n• Au moins un caractère miniscule\n• Au moins un chiffre\n• Au moins un symbole spécial");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if (jPasswordField1.getEchoChar()=='*'){
            jPasswordField1.setEchoChar((char) 0);
            jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hide.png")));
        }
        else{
            jPasswordField1.setEchoChar('*');
            jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/view.png")));
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if (jPasswordField2.getEchoChar()=='*'){
            jPasswordField2.setEchoChar((char) 0);
            jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hide.png")));
        }
        else{
            jPasswordField2.setEchoChar('*');
            jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/view.png")));
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionCompte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ajoutAdh;
    private javax.swing.JPanel ajoutPanel;
    private javax.swing.JPanel discPanel;
    private javax.swing.JPanel editPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel majAdh;
    private javax.swing.JPanel navPanel;
    private javax.swing.JPanel retourPanel;
    // End of variables declaration//GEN-END:variables
}
