



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aminb
 */
package gerer;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GestionLivre extends javax.swing.JFrame {
    
    Pattern isbnPattern=Pattern.compile("^[0-9]{13}$");
    Pattern titlePattern = Pattern.compile("^[0-9a-zA-z]+([\\s][0-9a-zA-z]+)*$");
    
    Connection con;
    Color selected=new Color(111,202,233);
    Color notselected=new Color(56,182,225);
    String currentCard="card2";
    Livre updateLivre;
    Livre affLivre;
    List<String> listeAuteurs;
    String[] arrayAuteurs;
    /**
     * Creates new form App
     * @param con
     */
    public GestionLivre(Connection con) {
        initComponents();
        this.con=con;}
    public GestionLivre() {
        initComponents();
        try{
            // Connect to DB
            String host = "jdbc:mysql://localhost:3306/biblio";
            String nName = "root";
            String uPass = "root";
            con= DriverManager.getConnection(host,nName,uPass);
            System.out.println("Connected to DB");
            Statement stmt = con.createStatement();
            String query1="SET information_schema_stats_expiry = 0;";
            stmt.executeUpdate(query1);
        }
        catch (SQLException err){
            System.out.println(err.getMessage());
        }
        getAuteurs();
    }
    
    public void setBackground(){
        ajoutPanel.setBackground(notselected);
        editPanel.setBackground(notselected);
    }
    
    public void clearUpdateLivre(){
        jTextField5.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jLabel15.setText("");
        jLabel16.setText("");
        jLabel18.setText("");
        jLabel20.setText("");
    }
    public void clearAjoutLivre(){
        jTextField2.setText("");
        jTextField3.setText("");
        jLabel3.setText("");
        jLabel4.setText("");
        jLabel24.setText("");
    }
    
    public final void getAuteurs(){
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        listeAuteurs = new ArrayList<>();
        try {
            Statement stmt = con.createStatement();
            String query = "SELECT * from auteur";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()){
                jComboBox1.addItem(rs.getInt("id_auteur")+": "+rs.getString("nomAut")+" "+rs.getString("prenomAut"));
                jComboBox2.addItem(rs.getInt("id_auteur")+": "+rs.getString("nomAut")+" "+rs.getString("prenomAut"));
                listeAuteurs.add(rs.getInt("id_auteur")+": "+rs.getString("nomAut")+" "+rs.getString("prenomAut"));
            }
            arrayAuteurs = new String[ listeAuteurs.size() ];
            listeAuteurs.toArray( arrayAuteurs );
        } 
        catch (SQLException err) {
            System.out.println(err.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();
        retourPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        ajoutPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        editPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        discPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        ajoutLivre = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        majLivre = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        affPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Livre");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navPanel.setBackground(new java.awt.Color(56, 182, 255));
        navPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        retourPanel.setBackground(new java.awt.Color(56, 182, 255));
        retourPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retourPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                retourPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                retourPanelMouseExited(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(18, 18, 18));
        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow.png"))); // NOI18N
        jLabel23.setText("     Retour");
        jLabel23.setHorizontalAlignment(JLabel.CENTER);

        javax.swing.GroupLayout retourPanelLayout = new javax.swing.GroupLayout(retourPanel);
        retourPanel.setLayout(retourPanelLayout);
        retourPanelLayout.setHorizontalGroup(
            retourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        retourPanelLayout.setVerticalGroup(
            retourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        navPanel.add(retourPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        ajoutPanel.setBackground(new java.awt.Color(110, 202, 233));
        ajoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajoutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajoutPanelMouseExited(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(7, 213, 224));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(JLabel.CENTER);
        jLabel10.setText("Ajout Livre");

        javax.swing.GroupLayout ajoutPanelLayout = new javax.swing.GroupLayout(ajoutPanel);
        ajoutPanel.setLayout(ajoutPanelLayout);
        ajoutPanelLayout.setHorizontalGroup(
            ajoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutPanelLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ajoutPanelLayout.setVerticalGroup(
            ajoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        navPanel.add(ajoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, 200, 45));

        editPanel.setBackground(new java.awt.Color(56, 182, 255));
        editPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editPanelMouseExited(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(64, 43, 100));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(JLabel.CENTER);
        jLabel11.setText("Editer Livre");

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        navPanel.add(editPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 45));

        discPanel.setBackground(new java.awt.Color(56, 182, 255));
        discPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                discPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                discPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                discPanelMouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(18, 18, 18));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/power.png"))); // NOI18N
        jLabel9.setText("     Deconnecter");
        jLabel9.setHorizontalAlignment(JLabel.CENTER);

        javax.swing.GroupLayout discPanelLayout = new javax.swing.GroupLayout(discPanel);
        discPanel.setLayout(discPanelLayout);
        discPanelLayout.setHorizontalGroup(
            discPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        discPanelLayout.setVerticalGroup(
            discPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        navPanel.add(discPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 406, 200, 45));

        getContentPane().add(navPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 451));

        mainPanel.setLayout(new java.awt.CardLayout());

        ajoutLivre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("ISBN");
        ajoutLivre.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 170, 40));
        ajoutLivre.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 180, 40));

        jLabel7.setText("Titre");
        ajoutLivre.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 170, 40));
        ajoutLivre.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 180, 40));

        jButton5.setText("Annuler");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        ajoutLivre.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 160, 40));

        jButton6.setText("Confirmer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        ajoutLivre.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 160, 40));

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        ajoutLivre.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 180, 30));

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        ajoutLivre.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 180, 30));

        jLabel24.setForeground(new java.awt.Color(0, 153, 0));
        ajoutLivre.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 360, 30));
        jLabel24.setHorizontalAlignment(JLabel.CENTER);

        jLabel8.setText("Nombre d'exemplaires");
        ajoutLivre.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 170, 40));
        ajoutLivre.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 180, 40));

        jLabel17.setText("Auteur");
        ajoutLivre.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 170, 40));
        ajoutLivre.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 180, 40));

        jLabel5.setBackground(new java.awt.Color(255, 0, 0));
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        ajoutLivre.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 180, 30));

        mainPanel.add(ajoutLivre, "card2");

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("ISBN");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 40));

        jLabel14.setText("Titre");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, 40));
        jPanel7.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 150, 40));

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 150, 30));
        jPanel7.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 150, 40));

        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 150, 30));

        jButton4.setText("Confirmer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 130, 40));

        jButton7.setText("Annuler");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 130, 40));
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 310, 30));

        jLabel13.setText("Nombre d'exemplaire");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, 40));
        jPanel7.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 150, 40));

        jLabel19.setText("Auteur");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, 40));
        jPanel7.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 150, 40));

        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 150, 30));

        jPanel8.setBorder(BorderFactory.createMatteBorder(0,1,0,0,Color.black));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/loupe.png"))); // NOI18N
        jLabel2.setText("ID");
        jLabel2.setHorizontalAlignment(JLabel.CENTER);
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 70, 50));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 157, 50));

        jButton1.setText("Inserer donnees");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 157, 35));

        jButton2.setText("Effacer Livre");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 157, 35));

        jButton3.setText("Afficher Emprunts");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 157, 35));

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 157, 20));

        javax.swing.GroupLayout majLivreLayout = new javax.swing.GroupLayout(majLivre);
        majLivre.setLayout(majLivreLayout);
        majLivreLayout.setHorizontalGroup(
            majLivreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(majLivreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        majLivreLayout.setVerticalGroup(
            majLivreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPanel.add(majLivre, "card3");

        affPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Empreint", "Id adherent", "Date Empreint", "Date Retour Prevue", "Date Retour"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        affPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 610, 320));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        affPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 570, 30));

        mainPanel.add(affPanel, "card4");

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Maj Livre Inserer Donnees
        jLabel16.setText("");
        Matcher matcher = isbnPattern.matcher(jTextField5.getText());
        boolean matchFound = matcher.find();
        if(!matchFound) {
            jLabel16.setText("ISBN invalide");
        }
        else {
            jLabel16.setText("");
            try{
                Statement stmt = con.createStatement();
                String query = "SELECT * from livre WHERE isbn='"+jTextField5.getText()+"'";
                ResultSet rs = stmt.executeQuery(query);
                if (rs.next()){
                    updateLivre = new Livre(jTextField5.getText(),con);
                    jTextField7.setText(updateLivre.getIsbn());
                    jTextField8.setText(updateLivre.getTitre());
                    jSpinner2.setValue(Livre.getNombreExemplaire(updateLivre.getIsbn(), con));
                    for (int i = 0; i < arrayAuteurs.length; i++) {
                        if(updateLivre.id_auteur==Integer.parseInt(String.valueOf(arrayAuteurs[i]).substring(0, 1))){
                            jComboBox1.setSelectedIndex(i);
                        }
                        
                    }
                }
                else{
                    jLabel16.setText("Aucun livre avec ce ISBN");
                }
            }
            catch(SQLException err){
                System.out.println("Erreur insertion adherent");
                System.out.println(err.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        clearUpdateLivre();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // Confirmer MAJ Adh
        jLabel15.setText("");jLabel21.setText("");jLabel18.setText("");jLabel16.setText("");jLabel20.setText("");
        Boolean t=true;
        Matcher matcher;
        
        if (updateLivre==null){
            jLabel16.setText("Aucun livre choisi");
            return;
        }
        
        matcher = isbnPattern.matcher(jTextField7.getText());
        if(!matcher.find()) {
            t=false;
            jLabel15.setText("ISBN invalide");
        }
        matcher = titlePattern.matcher(jTextField8.getText());
        if(!matcher.find()) {
            t=false;
            jLabel21.setText("Titre invalide");
        }
        if(Integer.parseInt(jSpinner2.getValue().toString())<0) {
            t=false;
            jLabel20.setText("Nombre invalide");
        }
        
        if (t){
            if (Livre.getNombreExemplaire(updateLivre.getIsbn(), con)-Integer.parseInt(jSpinner2.getValue().toString())>Livre.getNombreExemplaireFree(updateLivre.getIsbn(), con)){
                jLabel20.setText("<html>Ce livre n'a pas "+(Livre.getNombreExemplaire(updateLivre.getIsbn(), con)-Integer.parseInt(jSpinner2.getValue().toString()))+"<br>exemplaires libres</html>");
                t=false;
            }
            try{
                Statement stmt = con.createStatement();
                String query1 = "SELECT * FROM livre WHERE isbn='"+jTextField7.getText()+"'";
                ResultSet rs = stmt.executeQuery(query1);
                if (rs.next() && !jTextField7.getText().equals(updateLivre.getIsbn())){
                    t=false;
                    jLabel15.setText("ISBN deja utilisé");
                }
            }
            catch (SQLException err){
                System.out.println("Erreur ajout");
                System.out.println(err.getMessage());
            }
        }
        if (t){
            updateLivre.setIsbn(jTextField7.getText());
            updateLivre.setTitre(jTextField8.getText());
            updateLivre.setAuteur(Integer.parseInt(jComboBox1.getSelectedItem().toString().substring(0, 1)));
            updateLivre.updateDB(con);
            int exempDiff=Integer.parseInt(jSpinner2.getValue().toString())-Livre.getNombreExemplaire(updateLivre.getIsbn(),con);
            if(exempDiff>0){
                for (int i = 0; i < exempDiff; i++) {
                    System.out.println(i);
                    Exemplaire exemp = new Exemplaire(0, updateLivre.getIsbn(), con);
                }
            }
            if(exempDiff<0){
                try {
                    Statement stmt = con.createStatement();
                    String query="SELECT id_exemp FROM exemplaire WHERE isbn='"+updateLivre.getIsbn()+"' AND etat_exemp=0";
                    ResultSet rs = stmt.executeQuery(query);
                    for (int i = 0; i < -exempDiff; i++) {
                        rs.next();
                        Exemplaire.delDB(rs.getInt("id_exemp"), con);
                    }
                }
                catch (SQLException err) {
                    System.out.println(err.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // Supprimer Adh
        jLabel16.setText("");
        Matcher matcher = isbnPattern.matcher(jTextField5.getText());
        boolean matchFound = matcher.find();
        if(!matchFound) {
            jLabel16.setText("ISBN invalide");
            return;
        }
        try{
            Statement stmt = con.createStatement();
            String query = "SELECT * from livre WHERE isbn='"+jTextField5.getText()+"'";
            ResultSet rs = stmt.executeQuery(query);
            if (rs.next()){
                int input = JOptionPane.showConfirmDialog(null, "Confirmer la supression","Confirmation",JOptionPane.OK_CANCEL_OPTION);
                if (input==0){
                    jLabel16.setText("");
                    Livre.delDB(jTextField5.getText(), con);
                    JOptionPane.showMessageDialog(null, "Livre supprimé avec succès");
                }
            }
            else{
                jLabel16.setText("Aucun livre avec cette id");
            }
        }
        catch(SQLException err){
            System.out.println("Erreur suppression livre");
            System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        // Ajouter Adh Confirmer
        jLabel3.setText("");jLabel4.setText("");jLabel5.setText("");jLabel24.setText("");
        Boolean t=true;
        Matcher matcher;
        
        matcher = titlePattern.matcher(jTextField3.getText());
        if(!matcher.find()) {
            t=false;
            jLabel5.setText("Titre invalide");
        }
        
        matcher = isbnPattern.matcher(jTextField2.getText());
        if(!matcher.find()) {
            t=false;
            jLabel3.setText("ISBN invalide");
        }
        
        if(Integer.parseInt(jSpinner1.getValue().toString())<0) {
            t=false;;
            jLabel4.setText("Nombre invalide");
        }
        
        if (t){
            try{
                Statement stmt = con.createStatement();
                String query1 = "SELECT * FROM livre WHERE isbn='"+jTextField2.getText()+"'";
                ResultSet rs = stmt.executeQuery(query1);
                if (rs.next()){
                    t=false;
                    jLabel3.setText("ISBN deja existe");
                }
            }
            catch (SQLException err){
                System.out.println("Erreur ajout");
                System.out.println(err.getMessage());
            }
        }
        
        if (t){
           Livre livre = new Livre(jTextField2.getText(),jTextField3.getText(),Integer.parseInt((jComboBox2.getSelectedItem().toString().substring(0, 1))),con);
           jLabel24.setText("Livre cree avec succes");
            for (int i = 0; i < Integer.parseInt(jSpinner1.getValue().toString()); i++) {
                Exemplaire exemp = new Exemplaire(0,jTextField2.getText(),con);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        clearAjoutLivre();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void discPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discPanelMouseExited
        // TODO add your handling code here:
        discPanel.setBackground(notselected);
    }//GEN-LAST:event_discPanelMouseExited

    private void discPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discPanelMouseEntered
        // TODO add your handling code here:
        // Disconnect
        discPanel.setBackground(selected);
    }//GEN-LAST:event_discPanelMouseEntered

    private void editPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPanelMouseExited
        // TODO add your handling code here:
        if (!currentCard.equals("card3")){
            editPanel.setBackground(notselected);
        }
    }//GEN-LAST:event_editPanelMouseExited

    private void editPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPanelMouseEntered
        // TODO add your handling code here:
        editPanel.setBackground(selected);
    }//GEN-LAST:event_editPanelMouseEntered

    private void editPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPanelMouseClicked
        // TODO add your handling code here:
        // Editer Adherant
        clearAjoutLivre();
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card3");
        currentCard="card3";
        setBackground();
        editPanel.setBackground(selected);
    }//GEN-LAST:event_editPanelMouseClicked

    private void ajoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutPanelMouseClicked
        // TODO add your handling code here:
        // Ajouter Adherant
        clearUpdateLivre();
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card2");
        currentCard="card2";
        setBackground();
        ajoutPanel.setBackground(selected);
    }//GEN-LAST:event_ajoutPanelMouseClicked

    private void ajoutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutPanelMouseEntered
        // TODO add your handling code here:
        ajoutPanel.setBackground(selected);
    }//GEN-LAST:event_ajoutPanelMouseEntered

    private void ajoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutPanelMouseExited
        // TODO add your handling code here:
        if (!currentCard.equals("card2")){
            ajoutPanel.setBackground(notselected);
        }
    }//GEN-LAST:event_ajoutPanelMouseExited

    private void retourPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourPanelMouseExited
        // TODO add your handling code here:
        retourPanel.setBackground(notselected);
    }//GEN-LAST:event_retourPanelMouseExited

    private void retourPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourPanelMouseEntered
        // TODO add your handling code here:
        retourPanel.setBackground(selected);
    }//GEN-LAST:event_retourPanelMouseEntered

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            jLabel16.setText("");
            Matcher matcher = isbnPattern.matcher(jTextField5.getText());
            boolean matchFound = matcher.find();
            if(!matchFound) {
                jLabel16.setText("ID invalide");
                return;
            }
            Statement stmt = con.createStatement();
            Statement stmt2 = con.createStatement();
            String query = "SELECT * from livre WHERE isbn='"+jTextField5.getText()+"'";
            ResultSet rs = stmt.executeQuery(query);
            if (!rs.next()){
                jLabel16.setText("Aucun livre avec ce ISBN");
            }
            else{
                rs.close();
                affLivre=new Livre(jTextField5.getText(),con);
                query = "SELECT * FROM empreint WHERE id_exemp=(SELECT id_exemp FROM exemplaire WHERE isbn='"+jTextField5.getText()+"')";
                rs = stmt.executeQuery(query);
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                while(rs.next()){
                    jLabel25.setText("Empreints pour "+affLivre.getTitre()+" (id:"+affLivre.getIsbn()+")");
                    CardLayout card = (CardLayout)mainPanel.getLayout();
                    card.show(mainPanel, "card4");
                    currentCard="card4";
                    setBackground();
                    Date date_retour = rs.getDate("date_retour_reel");
                    String date;
                    if(null==date_retour){
                        date="Pas encore rendu";
                    }
                    else{
                        date = date_retour.toString();
                    }
                    Object row [] = {rs.getInt("id_emp"), rs.getInt("id_adhe"), rs.getDate("date_emp"), rs.getDate("date_retour_prevu"),date};
                    model.addRow(row);
                }
            }
        }
        catch (SQLException err) {
                System.out.println("Erreur affichage");
                System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void retourPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourPanelMouseClicked
        // TODO add your handling code here:
        if ("card4".equals(currentCard)){
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "card3");
            currentCard="card3";
            setBackground();
            editPanel.setBackground(selected);
        }
    }//GEN-LAST:event_retourPanelMouseClicked

    private void discPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discPanelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_discPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionLivre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel affPanel;
    private javax.swing.JPanel ajoutLivre;
    private javax.swing.JPanel ajoutPanel;
    private javax.swing.JPanel discPanel;
    private javax.swing.JPanel editPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel majLivre;
    private javax.swing.JPanel navPanel;
    private javax.swing.JPanel retourPanel;
    // End of variables declaration//GEN-END:variables
}
